### ISSUE TITLE
Rake is not a requirement and causes dependency chain issues with pdk

### ISSUE THREAD

**Issue by logicminds** [puppetlabs/dependency_checker#29]
**Describe the bug**
Rake is not required to use the library but the dependency causes pdk's Gemfile to fail when using `pdk bundle exec ruby -r 'puppet_litmus/rake_tasks'` commands`

Remove the rake dependency from the gemspec and list as a development dependency instead

**Comment by chelnak** [comment]
Closing as this issue seems to have been inactive for some time now.
