### ISSUE TITLE
undefined >= method caused by having module dependency using private forge and/or Authorization

### ISSUE THREAD

**Issue by cdenneen** [puppetlabs/dependency_checker#30]
**Describe the bug**
Running dependency checks fails.

**To Reproduce**
❯ /usr/local/lib/ruby/gems/2.7.0/bin/dependency-checker metadata.json -v
Traceback (most recent call last):
	26: from /usr/local/lib/ruby/gems/2.7.0/bin/dependency-checker:23:in `<main>'
	25: from /usr/local/lib/ruby/gems/2.7.0/bin/dependency-checker:23:in `load'
	24: from /usr/local/lib/ruby/gems/2.7.0/gems/dependency_checker-0.2.0/bin/dependency-checker:53:in `<top (required)>'
	23: from /usr/local/lib/ruby/gems/2.7.0/gems/dependency_checker-0.2.0/lib/dependency_checker/runner.rb:191:in `run_with_args'
	22: from /usr/local/lib/ruby/gems/2.7.0/gems/dependency_checker-0.2.0/lib/dependency_checker/runner.rb:41:in `run'
	21: from /usr/local/lib/ruby/gems/2.7.0/gems/dependency_checker-0.2.0/lib/dependency_checker/runner.rb:63:in `run_dependency_checks'
	20: from /usr/local/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:289:in `map'
	19: from /usr/local/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:386:in `work_in_processes'
	18: from /usr/local/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:446:in `create_workers'
	17: from /usr/local/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:446:in `each_with_index'
	16: from /usr/local/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:446:in `each'
	15: from /usr/local/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:447:in `block in create_workers'
	14: from /usr/local/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:456:in `worker'
	13: from /usr/local/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:456:in `fork'
	12: from /usr/local/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:465:in `block in worker'
	11: from /usr/local/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:485:in `process_incoming_jobs'
	10: from /usr/local/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:515:in `call_with_index'
	 9: from /usr/local/lib/ruby/gems/2.7.0/gems/dependency_checker-0.2.0/lib/dependency_checker/runner.rb:80:in `block in run_dependency_checks'
	 8: from /usr/local/lib/ruby/gems/2.7.0/gems/dependency_checker-0.2.0/lib/dependency_checker/runner.rb:146:in `get_dependencies_from_metadata'
	 7: from /usr/local/lib/ruby/gems/2.7.0/gems/dependency_checker-0.2.0/lib/dependency_checker/metadata_checker.rb:16:in `check_dependencies'
	 6: from /usr/local/lib/ruby/gems/2.7.0/gems/dependency_checker-0.2.0/lib/dependency_checker/metadata_checker.rb:16:in `map'
	 5: from /usr/local/lib/ruby/gems/2.7.0/gems/dependency_checker-0.2.0/lib/dependency_checker/metadata_checker.rb:19:in `block in check_dependencies'
	 4: from /usr/local/lib/ruby/gems/2.7.0/gems/semantic_puppet-1.0.4/lib/semantic_puppet/version_range.rb:322:in `include?'
	 3: from /usr/local/lib/ruby/gems/2.7.0/gems/semantic_puppet-1.0.4/lib/semantic_puppet/version_range.rb:322:in `any?'
	 2: from /usr/local/lib/ruby/gems/2.7.0/gems/semantic_puppet-1.0.4/lib/semantic_puppet/version_range.rb:322:in `block in include?'
	 1: from /usr/local/lib/ruby/gems/2.7.0/gems/semantic_puppet-1.0.4/lib/semantic_puppet/version_range.rb:573:in `include?'
/usr/local/lib/ruby/gems/2.7.0/gems/semantic_puppet-1.0.4/lib/semantic_puppet/version_range.rb:642:in `include?': undefined method `>=' for nil:NilClass (NoMethodError)

**Expected behaviour**
Should pass as metadata.json is valid.

**Environmental context**
**Version:**
**Ruby Version:**
**Module (+ Version):**

**Additional context**
I'm curious if this is due to some sort of fact that I'm using an internal forge and one of the dependencies is private? I have confirmed that `puppet bundle exec rake puppet config print module_repository and forge_authorization` are properly configured but curious if `dependency_checker` is using something else to set the `forge` `baseurl` and `authorization_token`?

**Comment by cdenneen** [comment]
Looks like via `pdk` or some other way `dependency_checker` needs a way to configure `pdk release` to use configurable settings for `puppet_forge` gem it uses:

`PuppetForge.host = "https://your-own-api.url/"` needs to be able to be configured and `PuppetForge::Connection.authorization = "<your-api-key-here>"` (https://github.com/puppetlabs/forge-ruby#configuration)

@sanfrancrisko would this be done here or back in pdk?

**Comment by cdenneen** [comment]
```json
{
  "name": "ap-apiproxy",
  "version": "0.1.2",
  "author": "ap",
  "summary": "api proxies",
  "license": "Apache-2.0",
  "source": "",
  "dependencies": [
    {
      "name": "puppetlabs-stdlib",
      "version_requirement": ">= 1.0.0 < 9.0.0"
    },
    {
      "name": "puppet-nodejs",
      "version_requirement": ">= 1.0.0 < 10.0.0"
    },
    {
      "name": "puppet-nginx",
      "version_requirement": ">= 1.0.0 < 4.0.0"
    },
    {
      "name": "ap-profile_base",
      "version_requirement": ">= 1.0.0 < 9.0.0"
    }
  ],
  "operatingsystem_support": [
    {
      "operatingsystem": "CentOS",
      "operatingsystemrelease": [
        "7"
      ]
    }
  ],
  "requirements": [
    {
      "name": "puppet",
      "version_requirement": ">= 6.21.0 < 8.0.0"
    }
  ],
  "pdk-version": "2.2.0",
  "template-url": "https://github.com/puppetlabs/pdk-templates#main",
  "template-ref": "tags/2.3.0-0-g8aaceff"
}
```

**Comment by sanfrancrisko** [comment]
Some additional context: https://puppetcommunity.slack.com/archives/C113FRBRU/p1636641466044900

**Comment by cdenneen** [comment]
@sanfrancrisko will assume that pdk will require this configuration at a minimum if a "premium" module becomes a dependency.

**Comment by sanfrancrisko** [comment]
Thanks for raising that question @cdenneen - having a chat with the forge team, and we'll do some digging on that ourselves, when we're looking in to this.

Will keep you in the loop

**Comment by sanfrancrisko** [comment]
So, think your analysis is right @cdenneen - we'll need to set the `PuppetForge.host` and `PuppetForge::Connection.authorization` parameters from the `dependency_checker` Gem, pull in this new version to PDK, then expose those params for configuration from the PDK side too.

**Comment by sanfrancrisko** [comment]
I have a PR pretty much complete, bar the acceptance tests. I've got something else critical on my plate, so my colleague is going to jump in and see if he can sort the weirdness with RSpec.

@david22swan Just to summarise:

- We have [two `expect_any_instance_of`](https://github.com/puppetlabs/dependency_checker/pull/31/files#diff-e9cdcfa9242da7966c23721f49707bcbd27e93073b8ec3bb6b7b4a142e85a985R58-R59) validations happening here
- These are [the two lines](https://github.com/puppetlabs/dependency_checker/pull/31/files#diff-03c397d560ae5e501719f710eced51566dccced5dc33dfaff3adce62745565d8R10-R11) being validated

Perhaps `expect_any_instance_of` is not the right matcher for me to be using? It might be worth switching to [allow_any_instance_of](https://relishapp.com/rspec/rspec-mocks/docs/working-with-legacy-code/any-instance)

**Comment by cdenneen** [comment]
@sanfrancrisko great thanks. How will this end up getting configured in pdk release? Inside pdk.yaml?
